---
title: "Krishna Blogs"
subtitle: "Exploring the intersection of actuarial science, data science, and analytics"
page-layout: full
toc: false
listing:
  - id: featured-posts
    contents: posts/*/*.qmd
    type: grid
    max-items: 3
    sort: "date desc"
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    fields: [image, date, title, subtitle, categories, author]
    image-height: 200px
    image-placeholder: "images/placeholder.jpg"
  - id: featured-projects
    contents: projects/*.qmd
    type: grid
    max-items: 3
    sort: "date desc"
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    fields: [image, title, subtitle, categories]
    image-height: 200px
    image-placeholder: "images/placeholder.jpg"
---

::: {.column-page}
::: {.hero-banner}
# Welcome to my Actuarial & Data Science Hub

I'm an actuarial science graduate student with a strong interest in data science and a commitment to becoming a fully credentialed actuary. This site serves as a portfolio of my projects, research, and ideas at the intersection of actuarial modeling, data analytics, and risk management. It's a space where I explore practical problems, experiment with data-driven solutions, and share my learning journey. 


[About Me](/about/){.btn .btn-primary .btn-lg role="button"}
[View Projects](/projects/){.btn .btn-secondary .btn-lg role="button"}
:::

## Featured Posts {.mt-5}

::: {#featured-posts}
:::

[View All Posts](/posts/){.btn .btn-outline-primary .mt-3}

## Featured Projects {.mt-5}

::: {#featured-projects}
:::

[View All Projects](/projects/){.btn .btn-outline-primary .mt-3}

## Areas of Expertise {.mt-5}

::: {.grid}
::: {.g-col-12 .g-col-md-4}
### Actuarial Science
- Risk modeling and assessment
- Insurance pricing and reserving
- Gratuaty Valuation
- Pension valuation
:::

::: {.g-col-12 .g-col-md-4}
### Data Science
- Machine learning applications
- Predictive modeling
- Statistical analysis
:::

::: {.g-col-12 .g-col-md-4}
### Data Analysis
- Data visualization
- Business intelligence
- Financial analysis
- Trend forecasting
:::
:::

## Newsletter {.mt-5}

Stay updated with the latest in actuarial science and data analytics.

<form class="row g-3">
  <div class="col-auto">
    <input type="email" class="form-control" id="emailInput" placeholder="Krishnakumarshrestha00@gmail.com">
  </div>
  <div class="col-auto">
    <button type="submit" class="btn btn-primary mb-3">Subscribe</button>
  </div>
</form>
:::
